const SOLUTIONS = [
    "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult", "after", "again",
    "agent", "agree", "ahead", "alarm", "album", "alert", "alike", "alive", "allow", "alone",
    "along", "alter", "among", "anger", "angle", "angry", "apart", "apple", "apply", "arena",
    "argue", "arise", "array", "aside", "asset", "avoid", "award", "aware", "badly", "baker",
    "bases", "basic", "basis", "beach", "began", "begin", "begun", "being", "below", "bench",
    "billy", "birth", "black", "blame", "blank", "blast", "blend", "bless", "blind", "block",
    "blood", "bloom", "blown", "board", "boost", "booth", "bound", "brain", "brand", "brave",
    "bread", "break", "breed", "brief", "bring", "broad", "broke", "brown", "brush", "build",
    "built", "bunch", "burst", "buyer", "cabin", "cable", "calif", "carry", "catch", "cause",
    "chain", "chair", "chart", "chase", "cheap", "check", "chest", "chief", "child", "china",
    "chose", "chunk", "church", "claim", "class", "clean", "clear", "click", "climb", "clock",
    "close", "cloth", "cloud", "coach", "coast", "could", "count", "court", "cover", "crack",
    "craft", "crash", "crazy", "cream", "crime", "crisp", "cross", "crowd", "crown", "curve",
    "cycle", "daily", "dance", "dated", "dealt", "death", "debut", "delay", "depth", "doing",
    "doubt", "dozen", "draft", "drain", "drama", "drank", "drawn", "dream", "dress", "dried",
    "drink", "drive", "drops", "drove", "drugs", "drunk", "dying", "early", "earth", "eaten",
    "eight", "elder", "elect", "elite", "empty", "enemy", "enjoy", "enter", "entry", "equal",
    "error", "essay", "event", "every", "exact", "exist", "extra", "faith", "false", "fault",
    "favor", "feast", "field", "fifth", "fifty", "fight", "final", "first", "fixed", "flame",
    "flash", "fleet", "flesh", "float", "flood", "floor", "fluid", "focus", "force", "forth",
    "forum", "found", "frame", "frank", "fraud", "fresh", "front", "frost", "fruit", "fully",
    "funny", "giant", "given", "glass", "globe", "glory", "going", "golden", "grace", "grade",
    "grain", "grand", "grant", "grape", "grasp", "grass", "grave", "great", "green", "grief",
    "gross", "group", "grown", "guard", "guess", "guest", "guide", "guilt", "happy", "harry",
    "harsh", "haven", "heart", "heavy", "hello", "hence", "henry", "horse", "hotel", "house",
    "human", "ideal", "image", "imply", "index", "inner", "input", "issue", "japan", "jimmy",
    "joint", "jones", "judge", "juice", "known", "label", "large", "laser", "later", "latin",
    "laugh", "layer", "learn", "lease", "least", "leave", "legal", "lemon", "level", "lewis",
    "light", "limit", "links", "lives", "local", "lodge", "logic", "loose", "lords", "lover",
    "lower", "lucky", "lunch", "lying", "magic", "major", "maker", "manor", "march", "maria",
    "match", "maybe", "mayor", "meant", "medal", "media", "melon", "mercy", "merge", "merit",
    "merry", "metal", "metro", "might", "minor", "minus", "mixed", "model", "money", "month",
    "moral", "motor", "mount", "mouse", "mouth", "moved", "movie", "music", "naive", "naked",
    "named", "nasty", "naval", "nerve", "never", "newly", "night", "noble", "noise", "north",
    "notch", "noted", "novel", "nurse", "occur", "ocean", "offer", "often", "olive", "onset",
    "opera", "orbit", "order", "organ", "other", "ought", "outer", "owned", "owner", "oxide",
    "panel", "panic", "paper", "party", "pasta", "paste", "patch", "pause", "peace", "peach",
    "pearl", "penny", "phase", "phone", "photo", "piano", "piece", "pilot", "pinch", "pitch",
    "place", "plain", "plane", "plant", "plate", "plaza", "point", "polar", "pound", "power",
    "press", "price", "pride", "prime", "print", "prior", "prize", "probe", "prone", "proof",
    "proud", "prove", "proxy", "pulse", "punch", "pupil", "queen", "quest", "quick", "quiet",
    "quite", "quota", "quote", "radar", "radio", "raise", "rally", "ranch", "range", "rapid",
    "ratio", "reach", "react", "ready", "realm", "rebel", "refer", "reign", "relax", "reply",
    "rider", "ridge", "rifle", "right", "risky", "rival", "river", "robin", "robot", "rocky",
    "roger", "roman", "rouge", "rough", "round", "route", "royal", "rugby", "ruled", "ruler",
    "rural", "sadly", "safer", "saint", "salad", "sales", "sandy", "satan", "sauce", "saved",
    "scale", "scare", "scene", "scope", "score", "screw", "sense", "serve", "setup", "seven",
    "shade", "shake", "shall", "shame", "shape", "share", "shark", "sharp", "sheep", "sheer",
    "sheet", "shelf", "shell", "shift", "shine", "shirt", "shock", "shoot", "shore", "short",
    "shown", "sight", "sigma", "sigma", "silly", "simon", "since", "sixth", "sixty", "sized",
    "skill", "skull", "slave", "sleep", "slice", "slide", "slope", "small", "smart", "smell",
    "smile", "smith", "smoke", "snake", "solar", "solid", "solve", "sorry", "sound", "south",
    "space", "spare", "spark", "speak", "speed", "spend", "spent", "spicy", "spine", "spite",
    "split", "spoke", "sport", "spots", "spray", "squad", "stack", "staff", "stage", "stake",
    "stamp", "stand", "stark", "start", "state", "steak", "steam", "steel", "steep", "steer",
    "stern", "stick", "still", "stock", "stone", "stood", "store", "storm", "story", "stove",
    "strip", "stuck", "study", "stuff", "style", "sugar", "suite", "sunny", "super", "surge",
    "swamp", "swear", "sweat", "sweep", "sweet", "swift", "swing", "swiss", "sword", "table",
    "tacit", "taken", "tales", "taste", "taxes", "teach", "teeth", "tempo", "tends", "tenor",
    "tense", "tenth", "terms", "terry", "tests", "texas", "thank", "theft", "their", "theme",
    "there", "these", "thick", "thief", "thing", "think", "third", "those", "three", "threw",
    "throw", "thumb", "tiger", "tight", "timer", "times", "tired", "title", "today", "token",
    "tommy", "topic", "total", "touch", "tough", "towel", "tower", "trace", "track", "tract",
    "trade", "trail", "train", "trait", "trash", "treat", "trend", "trial", "tribe", "trick",
    "tried", "tries", "troop", "truck", "truly", "trump", "trunk", "trust", "truth", "tulip",
    "tumor", "tutor", "twice", "twist", "tyler", "ultra", "uncle", "under", "undue", "union",
    "unity", "until", "upper", "upset", "urban", "urged", "usage", "usual", "valid", "value",
    "vapor", "vault", "vegas", "venue", "verge", "verse", "video", "view", "vigor", "viral",
    "virus", "visit", "vital", "vivid", "vocal", "vogue", "voice", "voter", "wagon", "waist",
    "waste", "watch", "water", "waved", "weary", "whale", "wheat", "wheel", "where", "which",
    "while", "white", "whole", "whose", "widow", "width", "wired", "witch", "woman", "women",
    "world", "worry", "worse", "worst", "worth", "would", "wound", "woven", "wrath", "wreck",
    "wrist", "write", "wrong", "wrote", "yacht", "yield", "young", "yours", "youth", "zebra",
    "zesty", "zones"
];

/** Built from valid-wordle-words.txt via `node scripts/build-wordlist.js` */
const VALID_GUESSES = new Set(VALID_GUESS_WORD_LIST);
for (const word of SOLUTIONS) {
    VALID_GUESSES.add(word);
}

function getRandomWord() {
    return SOLUTIONS[Math.floor(Math.random() * SOLUTIONS.length)].toUpperCase();
}

function isValidWord(word) {
    return VALID_GUESSES.has(word.toLowerCase());
}
